import {
  faUtensils,
  faUser,
  faStore,
  faSignOutAlt,
  faPlus,
  faTrash,
  faEdit,
  faCheckCircle,
  faTimesCircle,
  faSearch,
  faCircleNotch,
  faShoppingCart,
  faPhone,
} from '@fortawesome/free-solid-svg-icons';

export const Icons = {
  phone: faPhone,
  cart: faShoppingCart,
  logo: faUtensils,
  profile: faUser,
  kitchen: faStore,
  logout: faSignOutAlt,
  add: faPlus,
  delete: faTrash,
  edit: faEdit,
  inStock: faCheckCircle,
  outOfStock: faTimesCircle,
  search: faSearch,
  spinner: faCircleNotch,
};
