import {
  faUtensils,
  faUser,
  faStore,
  faSignOutAlt,
  faPlus,
  faTrash,
  faEdit,
  faCheckCircle,
  faTimesCircle,
  faSearch,
  faCircleNotch,
  faShoppingCart,
  faPhone,
  faMinus,
  faPenToSquare,
  faTrashCan,
  faArrowLeft,
  faExclamationCircle,
  faInfoCircle,
  faCamera,
  faImage,
  faList,
} from '@fortawesome/free-solid-svg-icons';

export const Icons = {
  menu: faList,
  camera: faCamera,
  image: faImage,
  logo: faUtensils,
  success: faCheckCircle,
  error: faExclamationCircle,
  info: faInfoCircle,
  back: faArrowLeft,
  editPen: faPenToSquare,
  trashCan: faTrashCan,
  phone: faPhone,
  cart: faShoppingCart,
  profile: faUser,
  kitchen: faStore,
  logout: faSignOutAlt,
  add: faPlus,
  delete: faTrash,
  edit: faEdit,
  inStock: faCheckCircle,
  outOfStock: faTimesCircle,
  search: faSearch,
  spinner: faCircleNotch,
  remove: faMinus,
};
