import {
  faUtensils,
  faUser,
  faStore,
  faSignOutAlt,
  faPlus,
  faTrash,
  faEdit,
  faCheckCircle,
  faTimesCircle,
  faSearch,
  faCircleNotch,
  faShoppingCart,
  faPhone,
  faMinus,
  faPenToSquare,
  faTrashCan,
  faArrowLeft,
  faExclamationCircle,
  faInfoCircle,
  faCamera,
  faImage,
  faPlusCircle,
  faClipboardList,
  faClose,
  faLocation,
  faCircle,
  faArrowRight,
  faReceipt,
  faNoteSticky,
} from '@fortawesome/free-solid-svg-icons';

export const Icons = {
  notes: faNoteSticky,
  receipt: faReceipt,
  arrowRight: faArrowRight,
  location: faLocation,
  circle: faCircle,
  checkCircle: faCheckCircle,
  close: faClose,
  menu: faClipboardList,
  camera: faCamera,
  image: faImage,
  logo: faUtensils,
  success: faCheckCircle,
  error: faExclamationCircle,
  info: faInfoCircle,
  back: faArrowLeft,
  editPen: faPenToSquare,
  trashCan: faTrashCan,
  phone: faPhone,
  cart: faShoppingCart,
  profile: faUser,
  kitchen: faStore,
  logout: faSignOutAlt,
  addCircled: faPlusCircle,
  delete: faTrash,
  edit: faEdit,
  inStock: faCheckCircle,
  outOfStock: faTimesCircle,
  search: faSearch,
  spinner: faCircleNotch,
  plus: faPlus,
  minus: faMinus,
  infoCircled: faInfoCircle,
};
